from flask import Flask, request, jsonify
import threading
from brain import Brain
from knowledge_base import init_db, create_mission, update_mission, get_mission, add_finding
from tools.nmap_agent import NmapAgent
import time

app = Flask(__name__)
brain = Brain()

# Initialize DB
init_db()

# Tool registry
TOOLS = {
    "nmap": NmapAgent(),
    # Add other agents here
}

def execute_plan(mission_id, plan):
    """
    Executes the plan generated by the Brain in a background thread.
    """
    mission = get_mission(mission_id)
    target = mission['target']

    for step in plan:
        tool_name = step.get("tool")
        params = step.get("params", {})

        # Ensure target is passed if missing
        if "target" not in params:
            params["target"] = target

        if tool_name in TOOLS:
            print(f"Executing {tool_name} with params: {params}")
            result = TOOLS[tool_name].run(params)

            # Log result
            add_finding(target, tool_name, "Scan Output", result, severity="INFO")

            # Let the brain learn from this
            brain.learn(result)
        else:
            print(f"Tool {tool_name} not found.")

    update_mission(mission_id, status="COMPLETED")

@app.route('/mission', methods=['POST'])
def start_mission():
    data = request.json
    target = data.get("target")
    goal = data.get("goal", "Find vulnerabilities")

    if not target:
        return jsonify({"error": "Target is required"}), 400

    mission_id = create_mission(target, goal)

    # Ask Brain for a plan
    decision = brain.think({"target": target}, goal)
    plan = decision.get("plan", [])
    thought = decision.get("thought", "")

    update_mission(mission_id, plan=plan)

    # Start execution in background
    thread = threading.Thread(target=execute_plan, args=(mission_id, plan))
    thread.start()

    return jsonify({
        "mission_id": mission_id,
        "status": "STARTED",
        "thought": thought,
        "plan": plan
    })

@app.route('/mission/<int:mission_id>', methods=['GET'])
def get_mission_status(mission_id):
    mission = get_mission(mission_id)
    if mission:
        return jsonify(mission)
    return jsonify({"error": "Mission not found"}), 404

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)
